repos:
-   repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.6.0
    hooks:
    -   id: pyproject-fmt
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.11.12
    hooks:
    -   id: ruff
        args:
        - --fix
    -   id: ruff-format
-   repo: local
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: python
        types_or:
        - python
        files: ^src/|^main.py$
        args:
        - -rn
        - -sn
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
    -   id: mypy
        name: mypy-source
        files: ^src/|^main.py$ 